ALTER TABLE Membership DROP CONSTRAINT Membership_MID;
	
ALTER TABLE Membership DROP CONSTRAINT Membership_TID;
	
ALTER TABLE Member DROP CONSTRAINT Member_Org;
	
ALTER TABLE File DROP CONSTRAINT File_TID;	
	
ALTER TABLE Team DROP CONSTRAINT Team_OID;

DROP TABLE Organization;

DROP TABLE Team;

DROP TABLE File;

DROP TABLE Member;

DROP TABLE Membership;